### PR TITLE
Initial draft of README.md

### PR DESCRIPTION
**Pull request by m14t**
Hi,

I'm interested in learning more about Solid and possibly lending a hand. I figured I would start by helping with some documentation.

Johan Bové (@johanbove on Gitter) suggested this basic format to get started with.

If you'd like to have a [GitHub Pull Request Template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) or any other features, please let me know!

Thanks in advance!

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks a lot @m14t. I'm actually in the process this week of finishing up the first release of this library. I already have a local draft of a README, and will incorporate some parts of what you have written.

**Comment by RubenVerborgh** [comment]
> If you'd like to have a [GitHub Pull Request Template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) or any other features, please let me know!

Actually, that would be helpful, and issue templates as well.
For PRs, I'd mainly like to understand what it adds and why, with a ref to the issue if applicable.
If the issue is a bug, I'd like to know actual behavior versus observed behavior, and their setup (version, browser, OS) if applicable.
If the issue is a feature request, a description is enough.

**Comment by m14t** [comment]
I'm on it.

Would you like to:
1. Close this PR and open a new one.
2. Revert the README.md commits and add new commits for the templates. (6 commits in total)
3. Delete the README.md commits on this branch and add new commits for the templates. (2 commits in total)

My preference is option 1.

**Comment by RubenVerborgh** [comment]
1 please, thanks :-)

**Pull request closed without merging**
